{
    'name': 'Network Drives',
    'version': '16.0.1.0.0',
    'summary': 'Manage and open network drives with VPN support',
    'description': 'A module to manage VPN connections and network drives with file paths.',
    'author': 'Your Name',
    'category': 'Tools',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/network_drive_views.xml',
        'views/driver_credential_views.xml',
        'views/vpn_views.xml',
        'data/network_drive_actions.xml',
        'data/vpn_actions.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}